language: ruby
rvm:
 - 2.4.1
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rspec test/
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c "CREATE USER travis;" -U postgres
  - psql -c "CREATE DATABASE go_case_db_test OWNER travis;"